### ISSUE TITLE
iCal-Export doesn't work

### ISSUE THREAD

**Issue by thomas-mc-work** [janrieke/contractmanager#15]
I have a contract that ends this year and is enabled to remind me for the end of it. I've enabled the contractmanager plugin in the iCal plugin settings. When I quit jameica then only the events of hibisbus get written to the `ics` file.

My version:
jameica 2.6.1
hibiscus 2.6.17
ical Plugin 2.7.0
contractmanager 0.5 (~~0.5.1 doesn't show up in the plugin manager~~ 0.5.1 shows up but jameica is unable to install it. It says there are missing dependencies although the list below says everything is fine)

**Comment by janrieke** [comment]
1. Do the ContractManager events show up in the Jameica calendar view?
2. Could you provide the logs for the 0.5.1 installation problem?

**Comment by thomas-mc-work** [comment]
1: No
2: 
![screenshot - 18 06 2016 - 20 20 49](https://cloud.githubusercontent.com/assets/6542498/16172903/b3f97208-3592-11e6-8d20-b7060bd9fc47.png)

I've got all write permissions as I'm the owner and the `w` flag is set.

**Comment by janrieke** [comment]
1. If the contract reminders do not show up in the Jameica calendar, that sounds like a bug in ContractManager.
2. Strange, because all dependencies are fulfilled. To me, this looks like a problem in Jameica.

To find out more about both problems, I need the log files on debug level. Debug logging can be activated in the Jameica settings ("Log level"). The log file is located in the Jameica data directory. I wrote you a mail if you do not want to post your logs here.

**Comment by thomas-mc-work** [comment]
I've sent them via e-mail to you.

**Comment by thomas-mc-work** [comment]
I think the jameica version was the cause - somehow. I've upgraded form `2.6.1` to `2.6.4` today and now both issues are gone!

Anyway, thank you for your help. And thank you for the plugin! I like it very much.

**Comment by janrieke** [comment]
Great that it works now.
